# Generated by Django 4.2.30 on 2026-07-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ticket',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
